# Generated by Django 3.2.5 on 2022-10-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='description',
        ),
    ]
