# Generated by Django 4.1.2 on 2022-11-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0004_review_guest_alter_review_rating"),
    ]

    operations = [
        migrations.RenameField(model_name="review", old_name="guest", new_name="name",),
        migrations.RemoveField(model_name="review", name="user",),
    ]
