# Generated by Django 4.1.2 on 2022-11-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0005_rename_guest_review_name_remove_review_user"),
    ]

    operations = [
        migrations.RenameField(model_name="review", old_name="name", new_name="user",),
    ]
