# Generated by Django 4.1.2 on 2022-11-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0006_rename_name_review_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.CharField(default=False, max_length=100),
        ),
    ]
