# Generated by Django 4.1.2 on 2022-11-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0007_alter_review_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=300)),
                ("size", models.CharField(max_length=100)),
                ("rooms", models.CharField(max_length=100)),
            ],
        ),
    ]
