# Generated by Django 4.1.2 on 2022-11-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0008_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="datecreated",
            field=models.CharField(max_length=100),
        ),
    ]
